### ISSUE TITLE
scrypt hash looks different in PHP72 and PHP74

### ISSUE THREAD

**Issue by jijo7thomas** [DomBlack/php-scrypt#58] opened 2020-12-01 10:41 UTC
Hash generated by the following function doesn't match when it is run from PHP72 and PHP74

$hash = scrypt('pass123','NaCl', 16384, 8, 1, 64);

Using version 1.4.2 from https://pecl.php.net/package/scrypt

**Comment by kocsismate** [comment] 2022-08-24 07:31
I'm closing this issue because https://github.com/DomBlack/php-scrypt/commit/f849379b6c689aca318d87e8a7a76b0e6c10fd52 couldn't reproduce the issue.

**Closed** 2022-08-24 07:31 UTC
